"use strict";
module.exports = function (app) {
  var abc = require("../Controller/controller");
  app.route("/profile").post(abc.newProfile).get(abc.listProfile);
  app.route("/deleteProfile/:id").delete(abc.deleteProfile);
  app.route("/updateProfile/:id").put(abc.updateProfile);
  app.route("/newRequirement").post(abc.newRequirement);
  app.route("/requirementViews").post(abc.requirementViews);
  app.route("/listRequirement").get(abc.listRequirement);
  app.route("/updateRequirement/:id").put(abc.updateRequirement);
  app.route("/deleteRequirement/:id").put(abc.deleteRequirement);
  // app.route("/deleteAllRequirement").delete(abc.deleteAllRequirement);
  app.route("/requirementById/:id").get(abc.requirementById);
  app.route("/requirementByUserId").post(abc.requirementByUserId);
  app.route("/paymentByUserId").post(abc.paymentByUserId);
  app.route("/findRequest").post(abc.findRequest);
  // app.route("/getByUserId").post(abc.getUser);
  // app.route("/getByFIrebaseId").post(abc.getByFirebaseId);
  app.route("/requestByUserId").post(abc.requestByUserId);
  app.route("/messageNotifiById").post(abc.requestByBody);
  app.route("/updateRequest/:id").put(abc.updateRequest);
  app.route("/requestById/:id").get(abc.requestById);
  app.route("/postTrackContainer").post(abc.trackingrequirement);
  app.route("/getTrackContainer").get(abc.listTracking);
  app.route("/trackByUserId/:id").get(abc.trackByUserId);
  app.route("/updateTracking/:id").put(abc.updateTracking);
  app.route("/Payment").post(abc.payment);
  app.route("/getPaymentDetails").get(abc.listPayment);
  app.route("/newRequest").post(abc.newrequest);
  app.route("/getRequest").get(abc.listRequest);
  app.route("/getAllRequests").get(abc.listAllRequests);
  app.route("/approveRequest/:id").put(abc.approved);
  app.route("/notApprovedRequest").get(abc.requestFalse);
  app.route("/requestApproved").get(abc.requestTrue);
  app.route("/deleteRequest/:id").delete(abc.deleteRequest);
  app.route("/getTrackingContainerById").post(abc.getTrackingContainerById);
  app.route("/profileById").post(abc.listProfileById);
  app.route("/usingContainer").get(abc.usingContainer);
  app.route("/supplyContainer").get(abc.supplyContainer);
  app.route("/issues").post(abc.newIssue).get(abc.listIssues);
  app.route("/admin").post(abc.newadmin).get(abc.getAdmin);
  app.route("/admin/login").post(abc.admin);
  app.route("/container").post(abc.newcontainer).get(abc.getContainer);
  app.route("/updateContainerByContainerId/:id").put(abc.updateContainer);
  // app.route("/deleteadmin/:id").delete(abc.deleteAdmin);
  app.route("/newRelease").post(abc.newrelease);
  app.route("/getReleaseByRequestId/:id").get(abc.getRelease);
  app.route("/dropRelease").delete(abc.dropRelease);
  // app.route("/deleteRelease/:id").delete(abc.deleteRelease);
  app.route("/getContainerByRequestId").post(abc.containerByRequestId);
  app.route("/multiple/:id").get(abc.gather);
  app.route("/contact").get(abc.getContact).post(abc.newContact);
  // app.route("/getRelease").post(abc.getRelease);
};
